    <?php
        $new_content = [
            "@extends(\"main\")\n",
            "@section(\"content\")\n",    
            "<div class=\"container\">\n\n",
            "\t@include('errors.list')\n\n",
            "\t<form method=\"POST\" action=\"/auth/register\">\n",
            "\t{!! csrf_field() !!}\n",
            "\t<h2 class=\"text-center  wowload fadeInUp no-margin-btm\">Create An Account</h2>\n",
            "\t<div class=\"row wowload fadeInLeftBig\">\n",
            "\t\t<div id=\"signupbox\" class=\"mainbox col-md-5 col-md-offset-4 col-sm-8 col-sm-offset-2 col-lg-4 col-lg-offset-4\">\n",
            "\t\t\t<div class=\"panel panel-info\">\n", 
            "\t\t\t\t<div class=\"panel-body\" >\n",
            "\t\t\t\t\t<div id=\"signupform\" class=\"form-horizontal\" role=\"form\">\n",
            "\t\t\t\t\t\t<div class=\"form-group\">\n",
            "\t\t\t\t\t\t\t<label for=\"name\" class=\"col-md-3 control-label\">Name</label>\n",
            "\t\t\t\t\t\t\t<div class=\"col-md-9\">\n",
            "\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"{{ old('name') }}\" name=\"name\" placeholder=\"Name Surname\" >\n",
            "\t\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t\t</div>\n",

            "\t\t\t\t\t\t<div class=\"form-group\">\n",
            "\t\t\t\t\t\t\t<label for=\"email\" class=\"col-md-3 control-label\">Email</label>\n",
            "\t\t\t\t\t\t\t<div class=\"col-md-9\">\n",
            "\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"{{ old('email') }}\" name=\"email\" placeholder=\"Email\" >\n",
            "\t\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t\t</div>\n",

            "\t\t\t\t\t\t<div class=\"form-group\">\n",
            "\t\t\t\t\t\t\t<label for=\"email\" class=\"col-md-3 control-label\">Password</label>\n",
            "\t\t\t\t\t\t\t<div class=\"col-md-9\">\n",
            "\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required name=\"password\" placeholder=\"Password\" >\n",
            "\t\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t\t</div>\n",

            "\t\t\t\t\t\t<div class=\"form-group\">\n",
            "\t\t\t\t\t\t\t<label for=\"email\" class=\"col-md-3 control-label\">Confirm Password</label>\n",
            "\t\t\t\t\t\t\t<div class=\"col-md-9\">\n",
            "\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required name=\"password_confirmation\" placeholder=\"Confirm Password\" >\n",
            "\t\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t\t<div>\n",
            "\t\t\t\t\t\t\t<button type=\"submit\">Register</button>\n",
            "\t\t\t\t\t\t</div>\n",
            "\t\t\t\t\t</div>\n",
            "\t\t\t\t</div>\n",
            "\t\t\t</div>\n",
            "\t\t</div>\n",
            "\t</div>\n",  
            "\t</form>\n", 
            "\t</div>\n",        
            "</section>\n",
            "@endsection\n"                 
        ];
?>